spring:
  application:
    name: toy

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/redis_toy
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true